# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/pnath/softwares/cmake-3.4.1-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/pnath/softwares/cmake-3.4.1-Linux-x86_64/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /scratch/parswa/mdcuda/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /scratch/parswa/mdcuda/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/pnath/softwares/cmake-3.4.1-Linux-x86_64/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/pnath/softwares/cmake-3.4.1-Linux-x86_64/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /scratch/parswa/mdcuda/src/CMakeFiles /scratch/parswa/mdcuda/src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /scratch/parswa/mdcuda/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cuMD.x

# Build rule for target.
cuMD.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cuMD.x
.PHONY : cuMD.x

# fast build rule for target.
cuMD.x/fast:
	$(MAKE) -f CMakeFiles/cuMD.x.dir/build.make CMakeFiles/cuMD.x.dir/build
.PHONY : cuMD.x/fast

FileIO.o: FileIO.cpp.o

.PHONY : FileIO.o

# target to build an object file
FileIO.cpp.o:
	$(MAKE) -f CMakeFiles/cuMD.x.dir/build.make CMakeFiles/cuMD.x.dir/FileIO.cpp.o
.PHONY : FileIO.cpp.o

FileIO.i: FileIO.cpp.i

.PHONY : FileIO.i

# target to preprocess a source file
FileIO.cpp.i:
	$(MAKE) -f CMakeFiles/cuMD.x.dir/build.make CMakeFiles/cuMD.x.dir/FileIO.cpp.i
.PHONY : FileIO.cpp.i

FileIO.s: FileIO.cpp.s

.PHONY : FileIO.s

# target to generate assembly for a file
FileIO.cpp.s:
	$(MAKE) -f CMakeFiles/cuMD.x.dir/build.make CMakeFiles/cuMD.x.dir/FileIO.cpp.s
.PHONY : FileIO.cpp.s

ThermostatBDP.o: ThermostatBDP.cpp.o

.PHONY : ThermostatBDP.o

# target to build an object file
ThermostatBDP.cpp.o:
	$(MAKE) -f CMakeFiles/cuMD.x.dir/build.make CMakeFiles/cuMD.x.dir/ThermostatBDP.cpp.o
.PHONY : ThermostatBDP.cpp.o

ThermostatBDP.i: ThermostatBDP.cpp.i

.PHONY : ThermostatBDP.i

# target to preprocess a source file
ThermostatBDP.cpp.i:
	$(MAKE) -f CMakeFiles/cuMD.x.dir/build.make CMakeFiles/cuMD.x.dir/ThermostatBDP.cpp.i
.PHONY : ThermostatBDP.cpp.i

ThermostatBDP.s: ThermostatBDP.cpp.s

.PHONY : ThermostatBDP.s

# target to generate assembly for a file
ThermostatBDP.cpp.s:
	$(MAKE) -f CMakeFiles/cuMD.x.dir/build.make CMakeFiles/cuMD.x.dir/ThermostatBDP.cpp.s
.PHONY : ThermostatBDP.cpp.s

global.o: global.cpp.o

.PHONY : global.o

# target to build an object file
global.cpp.o:
	$(MAKE) -f CMakeFiles/cuMD.x.dir/build.make CMakeFiles/cuMD.x.dir/global.cpp.o
.PHONY : global.cpp.o

global.i: global.cpp.i

.PHONY : global.i

# target to preprocess a source file
global.cpp.i:
	$(MAKE) -f CMakeFiles/cuMD.x.dir/build.make CMakeFiles/cuMD.x.dir/global.cpp.i
.PHONY : global.cpp.i

global.s: global.cpp.s

.PHONY : global.s

# target to generate assembly for a file
global.cpp.s:
	$(MAKE) -f CMakeFiles/cuMD.x.dir/build.make CMakeFiles/cuMD.x.dir/global.cpp.s
.PHONY : global.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cuMD.x"
	@echo "... FileIO.o"
	@echo "... FileIO.i"
	@echo "... FileIO.s"
	@echo "... ThermostatBDP.o"
	@echo "... ThermostatBDP.i"
	@echo "... ThermostatBDP.s"
	@echo "... global.o"
	@echo "... global.i"
	@echo "... global.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

